site_name: Документация PochtaAPI
site_description: "Библиотека для работы с API Почты России"
site_url: https://virenbar.ru/PochtaAPI/
copyright: Copyright &copy; 2023 Virenbar
theme:
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  language: ru
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
  font:
    text: "Fira Sans"
    code: "Fira Code"
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Включить тёмную тему
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Включить светлую тему
  custom_dir: overrides
extra:
  social:
    - icon: material/email-newsletter
      link: https://www.pochta.ru/
      name: Сайт Почты России
    - icon: simple/github
      link: https://github.com/Virenbar/PochtaAPI
  analytics:
    provider: yandex
    property: 87731504
  # analytics:
  #   provider: google
  #   property: G-XXXXXXXXXX
extra_css:
  - stylesheets/extra.css
repo_name: "Virenbar/PochtaAPI"
repo_url: https://github.com/Virenbar/PochtaAPI
edit_uri: edit/master/docs/
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - attr_list
  - toc:
      permalink: "#"
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
plugins:
  - search:
      lang:
        - en
        - ru
nav:
  - Описание: index.md
  - PochtaAPI:
      - Авторизация: authorization.md
      - Отслеживание: tracking.md
      - Отправка(WIP): otpravka.md
  - Ссылки: links.md
